openapi: 3.0.1
info:
  title: SpringBoot_Rest_API
  description: API Definition of SpringBoot_Rest_API
  version: 1.0.0
servers:
- url: http://localhost:8290/employee
paths:
  /emp:
    get:
      responses:
        default:
          description: Default response
  /add:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /update:
    put:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /delete/{empId}:
    delete:
      parameters:
      - name: empId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /getbyId/{empId}:
    get:
      parameters:
      - name: empId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
